# This file is the entry point to configure your own services.
# Files in the packages/ subdirectory configure your dependencies.

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices.html#use-parameters-for-application-configuration
parameters:
    stripe_secret_key: "%env(STRIPE_SECRET_KEY)%"
    stripe_webhook_secret: "%env(STRIPE_WEBHOOK_SECRET)%"
    frontend_url: "%env(FRONTEND_URL)%"
    jwtSecret: "%env(JWT_QRCODE_SECRET)%"
    fromEmail: "%env(MAIL_FROM_ADDRESS)%"

services:
    # default configuration for services in *this* file
    _defaults:
        autowire: true # Automatically injects dependencies in your services.
        autoconfigure: true # Automatically registers your services as commands, event subscribers, etc.

    # makes classes in src/ available to be used as services
    # this creates a service per class whose id is the fully-qualified class name
    App\:
        resource: "../src/"
        exclude:
            - "../src/DependencyInjection/"
            - "../src/Entity/"
            - "../src/Kernel.php"

    # State Processor pour Stripe Checkout
    App\State\TicketCheckoutProcessor:
        decorates: "api_platform.doctrine.orm.state.persist_processor"
        arguments:
            $decorated: "@.inner"
            $stripeSecretKey: "%stripe_secret_key%"
            $frontendUrl: "%frontend_url%"

    # Webhook Controller
    App\Controller\StripeWebhookController:
        arguments:
            $stripeSecretKey: "%stripe_secret_key%"
            $stripeWebhookSecret: "%stripe_webhook_secret%"
        tags: ["controller.service_arguments"]

    # Repository pour injection
    App\Repository\TicketRepository:
        factory: ["@doctrine", "getRepository"]
        arguments:
            - 'App\Entity\Ticket'

    # State Processors configuration
    App\State\RefundRequestProcessor:
        arguments:
            $persistProcessor: "@api_platform.doctrine.orm.state.persist_processor"

    App\State\TicketProcessor:
        decorates: api_platform.doctrine.orm.state.persist_processor
        arguments:
            $persistProcessor: '@App\State\TicketProcessor.inner'
        tags:
            - { name: "api_platform.state_processor", priority: 200 }

    App\State\DonationCheckoutProcessor:
        decorates: "api_platform.doctrine.orm.state.persist_processor"
        arguments:
            $decorated: '@App\State\DonationCheckoutProcessor.inner'
            $stripeSecretKey: "%stripe_secret_key%"
            $frontendUrl: "%frontend_url%"
        tags:
            - { name: "api_platform.state_processor", priority: 100 }

    App\Doctrine\CurrentUserExtension:
        tags:
            - {
                  name: "api_platform.doctrine.orm.query_extension.collection",
                  priority: 50,
              }

    # add more service definitions when explicit configuration is needed
    # please note that last definitions always *replace* previous ones
